name: ProDisplayTV
options:
  bundleIdPrefix: com.firat
  deploymentTarget:
    tvOS: 17.0
targets:
  ProDisplayTV:
    type: application
    platform: tvOS
    sources:
      - path: Sources
    resources:
      - path: Resources/Assets.xcassets
      - path: Resources/Patterns
        type: folder
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.firat.ProDisplayTV
      DEVELOPMENT_TEAM: VAW6FMKNP9
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_CFBundleDisplayName: "Test Your TV"
      INFOPLIST_KEY_CFBundleName: "Test Your TV"
