name: TestYourTV
options:
  bundleIdPrefix: com.firat
  deploymentTarget:
    tvOS: 17.0
targets:
  TestYourTV:
    type: application
    platform: tvOS
    sources:
      - path: Sources
      - path: Resources/Assets.xcassets
        buildPhase: resources
      - path: Resources/Patterns
        type: folder
        buildPhase: resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.firat.TestYourTV
      DEVELOPMENT_TEAM: VAW6FMKNP9
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_PREVIEWS: YES
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_KEY_CFBundleDisplayName: "Test Your TV"
      INFOPLIST_KEY_CFBundleName: "Test Your TV"
      MARKETING_VERSION: 1.0.0
      CURRENT_PROJECT_VERSION: 1
      INFOPLIST_KEY_GCSupportedGameControllers:
        - ProfileName: ExtendedGamepad
        - ProfileName: MicroGamepad
      INFOPLIST_KEY_GCSupportsControllerUserInteraction: YES
